### ISSUE TITLE
Implement monomials

### ISSUE THREAD

**Issue by blegat** [blegat/CondensedMatterSOS.jl#8]
See https://juliaalgebra.github.io/MultivariatePolynomials.jl/stable/types/#MultivariatePolynomials.monomials
So for instance, `monomials(variables, 2)` should generate all quadratic monomials.

**Comment by Jacupo** [comment]
I have opened a new branch. 
Now monomials works like this:
`monomials([sx[1],sy[1]], 2)=[im*sz[1],-im*sz[1]]`
In this case it returns two monomials of degree one even if the requested degree is `2`  because the multiplication lowers the degree.

`monomials([sx[1],sx[2]], 2)=[sx[1]*sx[2]]` 
In this case it returns one single monomial and not [sx[1]*sx[2],sx[2]*sx[1]] because they commute.

I did some small changes in the code too:
`unique()` did not work with `SpinMonomial` because `hash()` did not work on `SpinMonomial` in order to make it work I had to redefine `MP.variables(spin::SpinMonomial) = values(spin.variables)`
to `MP.variables(spin::SpinMonomial) = collect(values(spin.variables))`, because `values ` returns an iterator list while MP.hash expects it to return a vector.

**Comment by blegat** [comment]
Hashing should be fixed by https://github.com/blegat/CondensedMatterSOS.jl/pull/10.
I'd rather not collect for `MP.variables` if we can avoid it as it might slow things down.
